<?php

$parameters = [
    'db_driver'                         => 'pdo_mysql',
    'db_host'                           => 'localhost',
    'db_table_prefix'                   => null,
    'db_port'                           => '3306',
    'db_name'                           => 'leadsengage_apps119',
    'db_user'                           => 'root',
    'db_password'                       => 'dacam',
    'db_backup_tables'                  => 1,
    'db_backup_prefix'                  => 'bak_',
    'db_server_version'                 => '5.5.58-0ubuntu0.14.04.1',
    'mailer_from_name'                  => 'Sathish',
    'mailer_from_email'                 => 'sathish@dacamsys.com',
    'mailer_transport'                  => 'mautic.transport.sendgrid_api',
    'mailer_host'                       => null,
    'mailer_port'                       => null,
    'mailer_encryption'                 => null,
    'mailer_auth_mode'                  => null,
    'mailer_spool_type'                 => 'file',
    'mailer_spool_path'                 => '%kernel.root_dir%/spool/sathish',
    'secret_key'                        => '61fe7d5e17d03e585ebf52ff75224c30a47d449860607df686ddccfcd85fc2df',
    'site_url'                          => 'http://sathish.localhost/mauto/index.php',
    'cache_path'                        => '/var/www/mauto/app/cache/sathish',
    'log_path'                          => '/var/www/mauto/app/logs/sathish',
    'image_path'                        => 'media/images/sathish',
    'tmp_path'                          => '/var/www/mauto/app/../media/files/sathish',
    'api_enabled'                       => 0,
    'api_enable_basic_auth'             => false,
    'api_oauth2_access_token_lifetime'  => 60,
    'api_oauth2_refresh_token_lifetime' => 14,
    'api_batch_max_limit'               => '200',
    'upload_dir'                        => '/var/www/mauto/app/../media/files/sathish',
    'max_size'                          => '10',
    'cors_restrict_domains'             => 0,
    'cors_valid_domains'                => [
    ],
    'default_timezone'                    => 'Asia/Calcutta',
    'locale'                              => 'en_US',
    'email_frequency_number'              => 10,
    'email_frequency_time'                => 'MONTH',
    'mailer_is_owner'                     => 0,
    'background_import_if_more_rows_than' => 5000,
    'footer_text'                         => 'To make sure you keep getting these emails in your INBOX, please add {from_email} to your address book or whitelist us.<br />Want out of the loop? {unsubscribe_link}<br /><br />Our Postal Address: {postal_address}',
    'track_contact_by_ip'                 => true,
    'track_by_fingerprint'                => true,
];
